---
- name: First yaml
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: Create directory
  file:
    path: ./rak
    state: directory

- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: present

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started

- name: Copy
  template: src=index.html dest=/usr/share/nginx/html/index.html

- name: Call Rstart
  template: src=update.html dest=/usr/share/nginx/html/index.html
  notify:
    - Restart Nginx

