---
- name: First yaml
  become: yes
  apt:
    name:
      - python3-pip
    update_cache: yes

- name: Create directory
  file:
    path: ./rak
    state: directory

- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: absent

- name: Start nginx
  become: yes
  service:
    name: nginx
    state: started

# - name: Copy
#   template: src=index.html dest=/usr/share/nginx/html/index.html

# - name: Call Rstart
#   template: src=update.html dest=/usr/share/nginx/html/index.html
#   notify:
#     - Restart Nginx

- name: debug
  debug:
    var: package_name

- name: debug
  debug:
    msg: "Hi Rakshith poojary"
  when: is_enabled

- name: List
  debug:
    var: fruits[0]

- name: Dictionary
  debug:
    var: newfruits.apple

- name: registerss
  command: echo "{{ newfruits["apple"] }}"
  register: hi

- name: display register
  debug:
    var: hi.stdout

