#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/raksh
- name: Install nginx
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Stop Apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Create file
  file:
    path: /home/ubuntu/name.txt
    state: touch

- name : craete a new file using copy
  copy:
    dest: /home/ubuntu/nameone.txt
    content: |
      Hello World

- name: Create a user
  user:
    name: devops
    state: present

- name: Install multiple pkgs
  apt:
    name:
      - git
      - curl
    state: present
  when: ansible_os_family == "Debian"

- name: copy the file
  copy:
    src: /home/ubuntu/Ansible/script.py
    dest: /home/ubuntu/new.py

- name: Host machine info
  debug:
    msg:
      - "Hostname: {{ansible_hostname}}"
      - "Memory: {{ansible_memory_mb.real.total}}"
      - "OSfamily: {{ansible_os_family}}"
      
- name: Check disk usage
      shell: df -h
      register: disk_output

    - debug:
        var: disk_output.stdout
  
    - name: Install multiple packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - vim
    # if fike already there then don't paste
   # Even with force: yes, Ansible still checks if the file content changed.
#If the file is already identical, it won't copy again (idempotency).
    - name: Copy file
      copy:
        src: test.txt
        dest: /tmp/test.txt
        firce: no
        
    - name: Check disk usage
      shell: df -h / | awk 'NR==2 {print $5}'
      register: disk_usage

    - name: Show warning
      debug:
        msg: "Disk usage is high: {{ disk_usage.stdout }}"
      when: disk_usage.stdout | regex_replace('%','') | int > 80
